### ISSUE TITLE
LatLon.nearestPointOnSegment() not working properly?

### ISSUE THREAD

**Issue by AkimboEG** [mrJean1/PyGeodesy#4]
Hi mrJean1,

I think I've found an issue with the `nearestPointOnSegment` method in `sphericalNvector.LatLon`.

```python
>>> from PyGeodesy.geodesy.sphericalNvector import LatLon
>>> a = LatLon(0, 0)
>>> b = LatLon(0, 1)
>>> x = LatLon(1, 0)
>>> x.nearestPointOnSegment(a, b)
LatLon(00°00′00.0″N, 180°00′00.0″E)
```

Cheers,
Eilam

**Comment by mrJean1** [comment]
Correct, there was an issue and that has been fixed.  Also, there were no tests for that method and there are now, including your example.  Thank you for reporting the issue.

**Comment by AkimboEG** [comment]
:+1:

**Comment by AkimboEG** [comment]
Hi Jean,

Further testing with new version shows the issue is only partially resolved.
I've written this simple function to calculate the distance of a point from a segment.
```python
def dist_p_ab(p, a, b):
    """Calculate distance (in radians) from point p to segment (a, b)"""

    n = p.nearestPointOnSegment(a, b)
    d = p.distanceTo(n, radius=1)
    
    return d
```

I've then tested this over a grid of latitudes and longitudes spanning the entire globe (`lat = np.arange(-90, 90, 1); lon = np.arange(-180, 180, 1)`) and renderer the results as an image using matplotlib.

![figure_1](https://cloud.githubusercontent.com/assets/4570254/20346316/0b92e214-ac04-11e6-928d-04c6902727cf.png)

The following (unrelated) code also illustrates the issue:
```python
>>> from PyGeodesy.geodesy.sphericalNvector import LatLon
>>> LatLon(10, -140).nearestPointOnSegment(LatLon(0, 20), LatLon(0, 40))
LatLon(00°00′00.0″N, 140°00′00.0″W)
>>> 

It seems like current implementation is failing for a subset of points.

Cheers,
Eilam

**Comment by mrJean1** [comment]
This is suspicious and I'll need to look into this further.  It may take a few weeks, though.

**Comment by mrJean1** [comment]
Courtesy of the original author, antipodal points (on the same hemisphere) are now handled in the sphericalNvector.LatLon method isWithinExtent.

**Comment by AkimboEG** [comment]
That was significantly shorter than a few weeks :smiley:

![image](https://cloud.githubusercontent.com/assets/4570254/20382009/add63cca-acb2-11e6-9b94-aa2d8d447436.png)

**Comment by chrisveness** [comment]
Nice visualisation!
